## YAML Template.
---
version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 158911092652.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - docker build -t 258092/nomorequeue .
      - docker tag nomorequeue_backend:latest 158911092652.dkr.ecr.us-west-2.amazonaws.com/nomorequeue_backend:latest
      - docker push 158911092652.dkr.ecr.us-west-2.amazonaws.com/nomorequeue_backend:latest
